# Pretrained model path (local first, fallback to HuggingFace Hub if not found)
pretrained_model_path: "pretrained_model"

input_folder: "exp-results/ss-exp/vrnerf_20260205_062447/kitchen/input_images"
output_folder: "exp-results/diffi-enhance-exp" # Output root, final dir will be diffi_enhance_<timestamp>

iters: 3
image_sorted: true
group_size: 5
group_mode: "sequential" # sequential | sliding
group_stride: null # only used when group_mode=sliding
interp_frames: 3
seed: 123
num_train: null
train_distribution: "uniform" # uniform | ordered

# Device: "auto" | "cuda" | "cpu"
device: "cuda"

export_ply: true

# Difix3D enhancement settings
# difix_prompt: "clean rendering artifacts, enhance details, realistic texture, sharp edges, preserve original structure, no new objects"
difix_prompt: "remove degradation"
difix_num_inference_steps: 1
difix_timesteps: [199]
difix_guidance_scale: 0.75
