experiment:
  pretrained_model_path: "pretrained_model"
  num_context: 64
  camera_id: "20"  # used for vr-nerf

  metrics_dir: "exp-results/ttt-exp/nvs_compare"
  image_root_dir: "exp-results/ttt-exp"

# cover vrnerf_sampler.yaml
dense_sparse:
  pool_size: 72
  pool_stride: 3
  seed: 123
  images_subdir: "images-jpeg-1k"