model:
  ckpts: false
  ckpt_path: null

images:
  # input_folder: "examples/vrnerf/riverview"
  input_folder: "ss_inputs/input_images_20260129_070245_081577"
  slected_folder: null
  output_folder: null
  image_sorted: false
  interp_frames: 3

inference:
  iter_num: 5
